# Test only features
name: Test Features

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      # - name: Test
      #   run: |
      #     npm ci
      #     npm run test:features
